### ISSUE TITLE
Incomplete requirement.txt

### ISSUE THREAD

**Issue by JunCEEE** [twguest/FELpy#4]
I noticed that these packages are needed by `FELpy`, but not listed in the `requirement.txt`:
```
SciencePlots
h5py-wrapper
```
It would be nice if the `requirement.txt` can be updated.

**Comment by twguest** [comment]
Hi Jun,

I've updated the `requirements.txt` accordingly. Thanks.

Note I have now also merged the 'develop' branch updates into 'master'
